from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://qap-dev.konneqt.cloud/preview-apis")
    page.get_by_role("button", name="Sign in").click()
    page.get_by_placeholder("mail@example.com").click()
    page.get_by_placeholder("mail@example.com").fill("admin@gg.com")
    page.get_by_label("Email:").click()
    page.get_by_label("Email:").fill("133333")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("menuitem", name="APIs").click()
    page.get_by_role("button", name="New").click()
    page.get_by_text("Create from Scratch").click()
    page.get_by_label("API Name:").click()
    page.get_by_label("API Name:").fill("API-Pokemon 2")
    page.get_by_label("Type:").click()
    page.get_by_text("Public", exact=True).click()
    page.get_by_role("button", name="Create").click()
    expect(page.get_by_text("Success", exact=True)).to_be_visible()
    page.get_by_role("button", name="Add New Route").click()
    page.get_by_label("Name:", exact=True).click()
    page.get_by_label("Name:", exact=True).press("Control+a")
    page.get_by_label("Name:", exact=True).fill("ditto")
    page.get_by_text("Extra settings").click()
    page.locator(".ant-select-selection-overflow").click()
    page.get_by_title("HEAD", exact=True).locator("div").click()
    page.get_by_title("POST").locator("div").click()
    page.get_by_role("button", name="plus Add field").nth(1).click()
    page.locator("#expose_headers_0_value").click()
    page.locator("#expose_headers_0_value").click()
    page.locator("#expose_headers_0_value").fill("*Content-Length")
    page.locator("#expose_headers_1_value").click()
    page.locator("#expose_headers_1_value").click()
    page.locator("#expose_headers_1_value").fill("Content-Type")
    page.get_by_text("Backend", exact=True).click()
    page.get_by_label("Backend URI Path:").click()
    page.get_by_label("Backend URI Path:").fill("/api/v2/pokemon/ditto")
    page.get_by_text("JSON").click()
    page.get_by_text("No-op", exact=True).click()
    page.get_by_placeholder("host").click()
    page.get_by_placeholder("host").fill("https://pokeapi.co")
    page.get_by_role("button", name="Create").click()
    page.get_by_text("Health Check", exact=True).click()
    page.get_by_role("button", name="Run Health Check").click()
