import time
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://qap-dev.konneqt.cloud/preview-apis")
    page.get_by_role("button", name="Sign in").click()
    page.get_by_placeholder("mail@example.com").click()
    page.get_by_placeholder("mail@example.com").fill("admin@exemple.io")
    page.get_by_label("Email:").click()
    page.get_by_label("Email:").fill("jhddjdjdj")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("menuitem", name="APIs").click()
    page.get_by_role("button", name="New").click()
    page.get_by_text("Create from URL").click()
    page.get_by_placeholder("Ex: https://api-.example.com/").click()
    page.get_by_placeholder("Ex: https://api-.example.com/").fill("https://api.apis.guru/v2/specs/abstractapi.com/geolocation/1.0.0/openapi.json")
    page.get_by_role("button", name="Import").click()
    time.sleep(3)
    page.get_by_role("button", name="Create").click()
    page.goto("https://qap-dev.konneqt.cloud/admin/apis/details/ip-geolocation-api")
    expect(page.get_by_text("Success", exact=True)).to_be_visible()
    page.get_by_role("button", name="edit").click()
    page.goto("https://qap-dev.konneqt.cloud/admin/apis/edit/ip-geolocation-api")
    expect(page.get_by_role("tab", name="Settings").locator("span")).to_be_visible()
    page.get_by_text("Docs and Terms").click()
    expect(page.get_by_text("Main Documentation:")).to_be_visible()
    page.get_by_text("HTTP Methods").click()
    expect(page.get_by_role("button", name="Add New Route")).to_be_visible()
    page.get_by_text("Health Check", exact=True).click()
    page.get_by_role("button", name="Run Health Check").click()
    expect(page.get_by_role("columnheader", name="Backend Endpoint")).to_be_visible()
    page.get_by_text("OWASP").click()
    page.get_by_role("button", name="Scan for Vulnerabilities with").click()
    expect(page.get_by_role("heading", name="Security Issues")).to_be_visible()
